# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 545873f4682811d968a9fa479937ae8256ed9d0ebd1608349cf40d23944a74ded2094449f19f70ae1ac71924264cdd9723cf9176b3ae1495c7cbe80650e61084

test:
  secret_key_base: ed81c0df2f3e44f7a9cd4f9a21035766cbd1e5ee47710e634e4d6b3c61794755f90dbbc1dabfd1a0238245b2aa0dacbd585180583cf7a77f2f9a350d15516197

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
